
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package backend.analizadoresTerminal;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int EXIT = 18;
  public static final int LS = 4;
  public static final int CHMOD = 11;
  public static final int CP = 8;
  public static final int MOSTRAR_ARCHIVOS_A = 17;
  public static final int CONCATENACION = 14;
  public static final int FORMATO_DIRECCION__RELATIVA = 13;
  public static final int RM = 9;
  public static final int CD = 2;
  public static final int MV = 7;
  public static final int MKDIR = 6;
  public static final int FORMATO_DIRECCION_ABSOLUTA = 12;
  public static final int PWD = 3;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int IDENTIFICADOR = 15;
  public static final int RMDIR = 10;
  public static final int MOSTRAR_ARCHIVOS_L = 16;
  public static final int TOUCH = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CD",
  "PWD",
  "LS",
  "TOUCH",
  "MKDIR",
  "MV",
  "CP",
  "RM",
  "RMDIR",
  "CHMOD",
  "FORMATO_DIRECCION_ABSOLUTA",
  "FORMATO_DIRECCION__RELATIVA",
  "CONCATENACION",
  "IDENTIFICADOR",
  "MOSTRAR_ARCHIVOS_L",
  "MOSTRAR_ARCHIVOS_A",
  "EXIT"
  };
}

