
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package backend.analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIRECCION = 3;
  public static final int FECHA_DE_CREACION = 9;
  public static final int FORMATO_DIRECCION = 13;
  public static final int ES_FOLDER = 7;
  public static final int TRUE = 10;
  public static final int PERMISOS = 6;
  public static final int DOS_PUNTOS = 2;
  public static final int OCULTO = 17;
  public static final int FORMATO_FECHA = 14;
  public static final int NOMBRE = 5;
  public static final int TAMANO = 8;
  public static final int EOF = 0;
  public static final int FALSE = 11;
  public static final int error = 1;
  public static final int IDENTIFICADOR = 12;
  public static final int ENTERO = 18;
  public static final int DIRECCION_DE_PADRE = 4;
  public static final int FORMATO_HORA = 16;
  public static final int HORA = 15;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DOS_PUNTOS",
  "DIRECCION",
  "DIRECCION_DE_PADRE",
  "NOMBRE",
  "PERMISOS",
  "ES_FOLDER",
  "TAMANO",
  "FECHA_DE_CREACION",
  "TRUE",
  "FALSE",
  "IDENTIFICADOR",
  "FORMATO_DIRECCION",
  "FORMATO_FECHA",
  "HORA",
  "FORMATO_HORA",
  "OCULTO",
  "ENTERO"
  };
}

